import Config

# Configure your database
config :pauseai_ca, PauseAiCa.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pauseai_ca_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pauseai_ca, PauseAiCaWeb.Endpoint,
  # Bound to all interfaces so the site can be opened from a phone or tablet on
  # the same network. The port is set in config/runtime.exs.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2D+Q+JTh8ZT0cyUC0UD/S2QEBgbv+CargSVdhWRQw1rQB/B5StzpwS0bP26i7LhK",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pauseai_ca, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pauseai_ca, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :pauseai_ca, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Letters go to the sender, never to a member of parliament.
config :pauseai_ca, :campaign_rehearsal, true

# Local work is badged too, so a screenshot from dev is never mistaken for staging.
config :pauseai_ca, :display_env, "dev"
