defmodule PauseAiCa.Repo.Migrations.EnableQuizPublication do
  use Ecto.Migration

  def up do
    drop constraint(:quiz_question_drafts, :draft_only)

    create constraint(:quiz_question_drafts, :question_status,
             check: "status IN ('draft', 'published')"
           )

    alter table(:quiz_question_drafts) do
      add :published_editions, :map, null: false, default: %{}
      add :published_kind, :text
      add :published_topic, :text
      add :published_revision, :integer
      add :published_at, :utc_datetime_usec
      add :deleted_at, :utc_datetime_usec
    end

    alter table(:quiz_question_revisions) do
      add :topic, :text
      add :status, :text
      add :published_editions, :map
    end

    if Application.get_env(:pauseai_ca, :mail_environment) in [:dev, :test, :staging] do
      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-01', 'bengio-speed', 'research', 'factual', '{\"en\": {\"question\": \"Why does Yoshua Bengio argue that we should prepare for advanced AI risks despite uncertain timelines?\", \"answer\": \"Yoshua Bengio is a Université de Montréal professor, Mila founder and co-recipient of the 2018 Turing Award for deep-learning research. In his 2023 FAQ, he argues that unexpectedly rapid progress and slow societal adaptation justify preparing for risks while timelines remain uncertain.\", \"options\": [\"Progress has surprised researchers, while society and policy take time to adapt\", \"Safety rules can wait until advanced AI is deployed widely\", \"Unexpected progress lets us predict a reliable arrival date\"], \"source\": \"Yoshua Bengio · FAQ on Catastrophic AI Risks · 24 June 2023 · Q2–Q3\", \"url\": \"https://yoshuabengio.org/en/blog/faq-catastrophic-ai-risks\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"4/5 · Bengio’s name, Turing Award and Canadian academic connection give his own English FAQ substantial expert recognition. It has less independent editorial framing than a broadcast interview. Author’s own risk argument, published in 2023; recognize its date and distinguish argument from current measurement.\"}, \"fr\": {\"question\": \"Selon Bengio, qu’est-ce qui a pris les chercheurs par surprise?\", \"answer\": \"Yoshua Bengio est professeur à l’Université de Montréal, fondateur de Mila et colauréat du prix Turing 2018 pour ses travaux en apprentissage profond. Dans cette entrevue en français avec Patrice Roy, à Radio-Canada, il explique que la vitesse des progrès et certains comportements mal alignés ont surpris même des chercheurs préoccupés par les risques. Ce passage ne fixe pas une date certaine.\", \"options\": [\"La vitesse des progrès et certains comportements mal alignés\", \"Seulement le nombre d’applications\", \"Une date précise d’arrivée de la superintelligence\"], \"source\": \"Bengio–Patrice Roy · Radio-Canada · 1:40–2:15\", \"url\": \"https://www.youtube.com/watch?v=WSsggkm03uE&t=100s\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"5/5 · Recognizable Canadian public broadcaster and interviewer, with an established Quebec AI researcher in a substantial interview. This closely fits Olivier’s high-social-proof example. A journalistic interview provides an expert’s argument; it does not imply that the broadcaster endorses every claim. Duration alone does not establish accuracy.\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-02', 'research-acceleration', 'research', 'factual', '{\"en\": {\"question\": \"How could AI doing AI research accelerate further AI development?\", \"answer\": \"AI could help with experiments and software that improve successor systems. If those successors become better research assistants, improvements could feed back into further progress. Favaro and Clark discuss this possibility alongside constraints such as compute, energy and human review; rapid acceleration is a scenario, not a guaranteed outcome.\", \"options\": [\"Better systems could help build better successors, creating a feedback loop\", \"The feedback can begin only after every research task is automated\", \"Faster coding makes the whole research process equally faster\"], \"source\": \"Marina Favaro and Jack Clark · Anthropic Institute · When AI builds itself · page updated 18 September 2026\", \"url\": \"https://www.anthropic.com/institute/recursive-self-improvement\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"3/5 · A recognizable frontier AI lab and named specialist authors make this a useful primary explanation, but an AI developer may be perceived as commercially interested. Anthropic develops and sells AI. Its own measurements and policy preferences should be attributed; independent assessment would strengthen the public reading path.\"}, \"fr\": {\"question\": \"Pourquoi une IA capable de faire de la recherche en IA pourrait-elle changer le rythme des progrès?\", \"answer\": \"Bengio évoque la possibilité que l’IA fasse de la recherche en IA et accélère les progrès. Il souligne aussi l’incertitude des échéances et la possibilité de rencontrer des obstacles.\", \"options\": [\"Elle pourrait accélérer le travail qui améliore les systèmes suivants\", \"Elle garantirait un arrêt des progrès\", \"Elle fixerait une date certaine\"], \"source\": \"Bengio–Patrice Roy · 19:31–20:47; incertitude à 21:31\", \"url\": \"https://www.youtube.com/watch?v=WSsggkm03uE&t=1171s\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"5/5 · Recognizable Canadian public broadcaster and interviewer, with an established Quebec AI researcher in a substantial interview. This closely fits Olivier’s high-social-proof example. A journalistic interview provides an expert’s argument; it does not imply that the broadcaster endorses every claim. Duration alone does not establish accuracy.\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-03', 'future-systems', 'research', 'factual', '{\"en\": {\"question\": \"What is the book’s argument about the AI you use today?\", \"answer\": \"The authors distinguish present chatbots from more capable future systems. Their argument concerns what happens if development reaches systems substantially more capable than humans. This is an argument about future risk, not a demonstrated outcome.\", \"options\": [\"It concerns more capable future systems, rather than a claim that today’s chatbot will kill everyone\", \"Every chatbot already has unlimited physical power\", \"A friendly conversation proves a system is safe\"], \"source\": \"If Anyone Builds It · Introduction\", \"url\": \"https://ifanyonebuildsit.com/intro/are-you-suggesting-that-chatgpt-could-kill-us-all\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · Specialist authors explaining their own argument can be useful, but the source lacks the broad editorial recognition of a major Canadian broadcaster. Book authors and associated advocates have a position on the policy question. Verify the explanation’s supporting evidence separately.\"}, \"fr\": {\"question\": \"Quels systèmes sont au centre du risque d’extinction décrit dans ce livre?\", \"answer\": \"Les auteurs visent des systèmes futurs plus capables que les humains. Ils ne fixent pas de date. Les dommages actuels méritent aussi leurs propres explications. Il s’agit d’un argument sur un risque futur, dont l’issue reste incertaine.\", \"options\": [\"Les futurs systèmes aux capacités supérieures aux nôtres\", \"Toutes les conversations actuelles avec ChatGPT\", \"Uniquement les robots humanoïdes\"], \"source\": \"If Anyone Builds It · Introduction (anglais)\", \"url\": \"https://ifanyonebuildsit.com/intro/are-you-suggesting-that-chatgpt-could-kill-us-all\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · Specialist authors explaining their own argument can be useful, but the source lacks the broad editorial recognition of a major Canadian broadcaster. Book authors and associated advocates have a position on the policy question. Verify the explanation’s supporting evidence separately.\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-04', 'digital-effects', 'research', 'factual', '{\"en\": {\"question\": \"How could a digital AI system have effects outside a chat window?\", \"answer\": \"Software already influences physical events through people, networks and connected tools. The book argues that a much more capable system could use such channels in dangerous ways; the existence of those channels does not establish that every present system can do so.\", \"options\": [\"Through connected tools, people and infrastructure\", \"Only if its screen becomes a robot\", \"Digital systems cannot affect physical events\"], \"source\": \"If Anyone Builds It · Chapter 6\", \"url\": \"https://ifanyonebuildsit.com/6/how-will-ais-be-able-to-affect-us-if-theyre-digital\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · Specialist authors explaining their own argument can be useful, but the source lacks the broad editorial recognition of a major Canadian broadcaster. Book authors and associated advocates have a position on the policy question. Verify the explanation’s supporting evidence separately.\"}, \"fr\": {\"question\": \"Une IA doit-elle avoir un corps pour agir dans le monde?\", \"answer\": \"Les outils, les permissions et les intermédiaires humains peuvent relier un logiciel à des conséquences réelles. Leur ampleur dépend de ses capacités, de ses accès et des protections. Le livre examine comment des systèmes beaucoup plus capables pourraient utiliser ces voies.\", \"options\": [\"Non, des outils connectés ou des personnes peuvent agir pour elle\", \"Oui, elle doit toujours disposer d’un robot\", \"Oui, sinon elle peut seulement produire du texte\"], \"source\": \"If Anyone Builds It · Chapitre 6 (anglais)\", \"url\": \"https://ifanyonebuildsit.com/6/how-will-ais-be-able-to-affect-us-if-theyre-digital\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · Specialist authors explaining their own argument can be useful, but the source lacks the broad editorial recognition of a major Canadian broadcaster. Book authors and associated advocates have a position on the policy question. Verify the explanation’s supporting evidence separately.\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-05', 'incident-evidence', 'incidents', 'factual', '{\"en\": {\"question\": \"What should you check before drawing a conclusion from an incident?\", \"answer\": \"A controlled test, a deployed incident and a forecast provide different kinds of evidence. Check the documented conditions and limitations before generalizing.\", \"options\": [\"The system, conditions, observations and limitations\", \"Only its headline\", \"Whether it confirms my existing view\"], \"source\": \"Warning shot · developments and sources\", \"url\": \"/en/warning-shot#developments\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · A PauseAI compilation helps organize sources but supplies little independent social proof on its own. The actual incident report or evaluation should be visible beside the question. Advocacy framing; individual reports may deserve different ratings. Do not assign the compilation’s score to every linked source.\"}, \"fr\": {\"question\": \"Que faut-il vérifier avant de tirer une conclusion d’un incident?\", \"answer\": \"Un test contrôlé, un incident déployé et une prévision apportent des informations différentes. Consultez les conditions et les limites documentées avant de généraliser.\", \"options\": [\"Le système, les conditions, les observations et les limites\", \"Seulement son titre\", \"Si le récit confirme déjà mon opinion\"], \"source\": \"Dossiers et sources du signal d’alarme\", \"url\": \"/fr/signal-d-alarme#developments\", \"correct\": 0, \"notes\": \"\", \"action\": \"\", \"social_proof\": \"2/5 · A PauseAI compilation helps organize sources but supplies little independent social proof on its own. The actual incident report or evaluation should be visible beside the question. Advocacy framing; individual reports may deserve different ratings. Do not assign the compilation’s score to every linked source.\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-06', 'treaty-verification', 'treaty', 'factual', '{\"en\": {\"question\": \"Which question makes a treaty proposal more concrete?\", \"answer\": \"A proposal needs to specify what is limited, how compliance is checked and how violations are addressed. Explore those choices in our strategy.\", \"options\": [\"How would compliance be verified and violations addressed?\", \"Does the word treaty guarantee safety?\", \"Can coordination be avoided entirely?\"], \"source\": \"PauseAI Canada strategy\", \"url\": \"/en/strategy\", \"correct\": 0, \"notes\": \"\", \"action\": \"\"}, \"fr\": {\"question\": \"Quelle question rend une proposition de traité plus concrète?\", \"answer\": \"Une proposition doit préciser ce qui serait limité, comment contrôler les engagements et comment répondre aux violations. Examinez ces choix dans notre stratégie.\", \"options\": [\"Comment vérifier le respect des engagements et répondre aux violations?\", \"Est-ce que le mot traité suffit à assurer la sécurité?\", \"Peut-on éviter toute coordination?\"], \"source\": \"Stratégie de PauseIA Canada\", \"url\": \"/fr/strategie\", \"correct\": 0, \"notes\": \"\", \"action\": \"\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )

      execute(
        "INSERT INTO quiz_question_drafts (id,review_id,concept_id,topic,kind,editions,inserted_at,updated_at) VALUES (gen_random_uuid(), 'LEARN-Q-07', 'stop-button', 'research', 'discussion', '{\"en\": {\"question\": \"Would a STOP button be enough to keep a very powerful AI under control?\", \"answer\": \"Explore four questions: how danger would be detected in time; who would have authority to stop the system; which copies and connected services would need stopping; and what tests would demonstrate reliable shutdown. Feasibility depends on the system and its deployment.\", \"options\": [], \"source\": \"If Anyone Builds It · Can we just pull the plug?\", \"url\": \"https://ifanyonebuildsit.com/6/can-we-just-pull-the-plug\", \"correct\": null, \"notes\": \"\", \"action\": \"\"}, \"fr\": {\"question\": \"Un bouton STOP suffirait-il à garder le contrôle d’une IA très puissante?\", \"answer\": \"Examinez quatre questions : comment détecter le danger à temps; qui aurait l’autorité d’arrêter le système; quelles copies et quels services connectés faudrait-il arrêter; quels tests démontreraient que l’arrêt fonctionne. La faisabilité dépend du système et de son déploiement.\", \"options\": [], \"source\": \"If Anyone Builds It · Peut-on couper le courant? (anglais)\", \"url\": \"https://ifanyonebuildsit.com/6/can-we-just-pull-the-plug\", \"correct\": null, \"notes\": \"\", \"action\": \"\"}}'::jsonb, now(), now()) ON CONFLICT (concept_id) DO NOTHING"
      )
    end
  end

  def down do
    drop constraint(:quiz_question_drafts, :question_status)
    create constraint(:quiz_question_drafts, :draft_only, check: "status = 'draft'")

    alter table(:quiz_question_drafts) do
      remove :published_editions
      remove :published_kind
      remove :published_topic
      remove :published_revision
      remove :published_at
      remove :deleted_at
    end

    alter table(:quiz_question_revisions) do
      remove :topic
      remove :status
      remove :published_editions
    end
  end
end
